// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLwI3rLvp3PXO_QlA1r2e5fJ99zFiAj7Y',
    appId: '1:352478951229:web:wordrobe-chat-web',
    messagingSenderId: '352478951229',
    projectId: 'wordrobe-chat',
    authDomain: 'wordrobe-chat.firebaseapp.com',
    storageBucket: 'wordrobe-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLwI3rLvp3PXO_QlA1r2e5fJ99zFiAj7Y',
    appId: '1:352478951229:android:11a68b4fca7f69b32d3754',
    messagingSenderId: '352478951229',
    projectId: 'wordrobe-chat',
    storageBucket: 'wordrobe-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Dv2sM5Y8A0VGVIjwd65nRGDbCSL4BL8',
    appId: '1:352478951229:ios:335fae394671b9a82d3754',
    messagingSenderId: '352478951229',
    projectId: 'wordrobe-chat',
    storageBucket: 'wordrobe-chat.firebasestorage.app',
    iosBundleId: 'com.wardrobe-chat.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Dv2sM5Y8A0VGVIjwd65nRGDbCSL4BL8',
    appId: '1:352478951229:ios:335fae394671b9a82d3754',
    messagingSenderId: '352478951229',
    projectId: 'wordrobe-chat',
    storageBucket: 'wordrobe-chat.firebasestorage.app',
    iosBundleId: 'com.wardrobe-chat.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLwI3rLvp3PXO_QlA1r2e5fJ99zFiAj7Y',
    appId: '1:352478951229:web:wordrobe-chat-web',
    messagingSenderId: '352478951229',
    projectId: 'wordrobe-chat',
    authDomain: 'wordrobe-chat.firebaseapp.com',
    storageBucket: 'wordrobe-chat.firebasestorage.app',
  );
}
