// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4jwik0gRdcGYvsqn5WmI6IuW3BplcI6o',
    appId: '1:306420873549:web:your-web-app-id',
    messagingSenderId: '306420873549',
    projectId: 'wordrope-f31e5',
    authDomain: 'wordrope-f31e5.firebaseapp.com',
    storageBucket: 'wordrope-f31e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4jwik0gRdcGYvsqn5WmI6IuW3BplcI6o',
    appId: '1:306420873549:android:27bb6637f5848c16565f04',
    messagingSenderId: '306420873549',
    projectId: 'wordrope-f31e5',
    storageBucket: 'wordrope-f31e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-FZnI1GyWIh1TFrCCkBw8XzNy6utcK7s',
    appId: '1:306420873549:ios:87693de94330a6f8565f04',
    messagingSenderId: '306420873549',
    projectId: 'wordrope-f31e5',
    storageBucket: 'wordrope-f31e5.firebasestorage.app',
    iosBundleId: 'com.wardrobe.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-FZnI1GyWIh1TFrCCkBw8XzNy6utcK7s',
    appId: '1:306420873549:ios:87693de94330a6f8565f04',
    messagingSenderId: '306420873549',
    projectId: 'wordrope-f31e5',
    storageBucket: 'wordrope-f31e5.firebasestorage.app',
    iosBundleId: 'com.wardrobe.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4jwik0gRdcGYvsqn5WmI6IuW3BplcI6o',
    appId: '1:306420873549:web:your-web-app-id',
    messagingSenderId: '306420873549',
    projectId: 'wordrope-f31e5',
    authDomain: 'wordrope-f31e5.firebaseapp.com',
    storageBucket: 'wordrope-f31e5.firebasestorage.app',
  );
}

