import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:provider/provider.dart';
import '../providers/wardrobe_provider.dart';
import '../providers/suggestion_provider.dart';
import '../models/wardrobe.dart';
import '../models/user_profile.dart';
import '../services/user_service.dart';
import '../services/suggestion_service.dart';
import '../services/notification_service.dart';
import '../widgets/profile_completion_modal.dart';
import '../widgets/account_settings_dialog.dart';
import 'create_wardrobe_screen.dart';
import 'wardrobe_detail_screen.dart';
import 'suggestion_screen.dart';
import 'chat_screen.dart';

class WelcomeScreen extends StatefulWidget {
  const WelcomeScreen({super.key});

  @override
  State<WelcomeScreen> createState() => _WelcomeScreenState();
}

class _WelcomeScreenState extends State<WelcomeScreen>
    with SingleTickerProviderStateMixin {
  late AnimationController _animationController;
  late Animation<double> _fadeAnimation;
  late Animation<Offset> _slideAnimation;
  UserProfile? _userProfile;

  @override
  void initState() {
    super.initState();
    _setupAnimations();
    _loadWardrobes();
    _checkProfileCompleteness();
    _initializeNotificationsAndSuggestions();
  }

  /// Initialize notifications and check for daily suggestions
  Future<void> _initializeNotificationsAndSuggestions() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) return;

    try {
      // Schedule daily notification if not already scheduled
      await NotificationService.scheduleDailySuggestionNotification();

      // Check if today's suggestion exists, if not generate it
      await SuggestionService.autoGenerateDailySuggestion(user.uid);

      // Load today's suggestion in the provider
      if (mounted) {
        final suggestionProvider = context.read<SuggestionProvider>();
        await suggestionProvider.loadTodaySuggestion(user.uid);
      }
    } catch (e) {
      debugPrint('Failed to initialize notifications and suggestions: $e');
    }
  }

  Future<void> _checkProfileCompleteness() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) return;

    try {
      final profile = await UserService.getUserProfile(user.uid);

      if (mounted) {
        setState(() {
          _userProfile = profile;
        });

        // Check if profile is incomplete and show modal
        if (profile == null || !profile.isComplete) {
          WidgetsBinding.instance.addPostFrameCallback((_) {
            _showProfileCompletionModal();
          });
        }
      }
    } catch (e) {
      // Handle error silently or show error message if needed
    }
  }

  Future<void> _showProfileCompletionModal() async {
    if (!mounted) return;

    final result = await showDialog<bool>(
      context: context,
      barrierDismissible: false, // Prevent dismissing without completing
      builder: (context) => const ProfileCompletionModal(),
    );

    // If profile was saved successfully, reload the profile and refresh the screen
    if (result == true && mounted) {
      await _checkProfileCompleteness();
      setState(() {}); // Trigger rebuild to show updated welcome message
    }
  }

  void _loadWardrobes() {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        context.read<WardrobeProvider>().loadWardrobes(user.uid);
      });
    }
  }

  Future<void> _refreshWardrobes() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null && mounted) {
      await context.read<WardrobeProvider>().loadWardrobes(user.uid);
    }
  }

  void _setupAnimations() {
    _animationController = AnimationController(
      duration: const Duration(milliseconds: 1500),
      vsync: this,
    );

    _fadeAnimation = Tween<double>(
      begin: 0.0,
      end: 1.0,
    ).animate(CurvedAnimation(
      parent: _animationController,
      curve: const Interval(0.0, 0.6, curve: Curves.easeIn),
    ));

    _slideAnimation = Tween<Offset>(
      begin: const Offset(0, 0.3),
      end: Offset.zero,
    ).animate(CurvedAnimation(
      parent: _animationController,
      curve: const Interval(0.2, 0.8, curve: Curves.easeOut),
    ));

    _animationController.forward();
  }

  Future<void> _deleteWardrobe(Wardrobe wardrobe) async {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) return;

    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Wardrobe'),
        content: Text(
            'Are you sure you want to delete "${wardrobe.title}"? This action cannot be undone.'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text('Delete'),
          ),
        ],
      ),
    );

    if (confirmed == true && mounted) {
      final provider = context.read<WardrobeProvider>();

      // Show loading
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (context) => const Center(
          child: CircularProgressIndicator(),
        ),
      );

      await provider.deleteWardrobe(user.uid, wardrobe.id);

      if (mounted) {
        Navigator.pop(context); // Close loading dialog

        if (!mounted) return;

        if (provider.errorMessage == null) {
          // Reload wardrobes to update UI
          await provider.loadWardrobes(user.uid);

          if (!mounted) return;
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Wardrobe deleted successfully'),
              backgroundColor: Colors.green,
            ),
          );
        } else {
          if (!mounted) return;
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(provider.errorMessage!),
              backgroundColor: Colors.red,
            ),
          );
        }
      }
    }
  }

  @override
  void dispose() {
    _animationController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final user = FirebaseAuth.instance.currentUser;
    final phoneNumber = user?.phoneNumber ?? 'Unknown';
    final userName = _userProfile?.name;

    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            colors: [Color(0xFF7C3AED), Color(0xFFA855F7)],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
        ),
        child: SafeArea(
          child: Column(
            children: [
              // Header with Sign Out button
              Padding(
                padding:
                    const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const SizedBox(width: 40), // Balance
                    const Text(
                      'My Wardrobes',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 20,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        IconButton(
                          icon: const Icon(Icons.settings, color: Colors.white),
                          onPressed: () {
                            showDialog(
                              context: context,
                              builder: (context) =>
                                  const AccountSettingsDialog(),
                            );
                          },
                          tooltip: 'Account Settings',
                        ),
                        IconButton(
                          icon: const Icon(Icons.chat, color: Colors.white),
                          onPressed: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (context) => const ChatScreen(),
                              ),
                            );
                          },
                          tooltip: 'Chat Assistant',
                        ),
                      ],
                    ),
                  ],
                ),
              ),

              Expanded(
                child: AnimatedBuilder(
                  animation: _animationController,
                  builder: (context, child) {
                    return FadeTransition(
                      opacity: _fadeAnimation,
                      child: SlideTransition(
                        position: _slideAnimation,
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            const SizedBox(height: 20),

                            // Success Icon
                            Center(
                              child: Container(
                                width: 120,
                                height: 120,
                                decoration: BoxDecoration(
                                  color: Colors.white.withValues(alpha: 0.15),
                                  borderRadius: BorderRadius.circular(30),
                                  boxShadow: [
                                    BoxShadow(
                                      color:
                                          Colors.black.withValues(alpha: 0.1),
                                      blurRadius: 20,
                                      offset: const Offset(0, 10),
                                    ),
                                  ],
                                ),
                                child: const Icon(
                                  Icons.check_circle,
                                  size: 60,
                                  color: Colors.white,
                                ),
                              ),
                            ),

                            const SizedBox(height: 20),

                            // Welcome Message
                            Text(
                              userName != null && userName.isNotEmpty
                                  ? 'Welcome, $userName!'
                                  : 'Welcome to Wardrobe!',
                              style: Theme.of(context)
                                  .textTheme
                                  .headlineLarge
                                  ?.copyWith(
                                    color: Colors.white,
                                    fontWeight: FontWeight.bold,
                                    fontSize: 32,
                                  ),
                              textAlign: TextAlign.center,
                            ),

                            const SizedBox(height: 8),

                            Text(
                              userName != null && userName.isNotEmpty
                                  ? 'You have successfully logged in to your account.'
                                  : 'You have successfully logged in to your account.',
                              style: Theme.of(context)
                                  .textTheme
                                  .titleMedium
                                  ?.copyWith(
                                    color: Colors.white.withValues(alpha: 0.9),
                                    fontSize: 16,
                                  ),
                              textAlign: TextAlign.center,
                            ),

                            const SizedBox(height: 8),

                            Text(
                              'Phone: $phoneNumber',
                              style: Theme.of(context)
                                  .textTheme
                                  .bodyLarge
                                  ?.copyWith(
                                    color: Colors.white.withValues(alpha: 0.8),
                                    fontSize: 14,
                                  ),
                              textAlign: TextAlign.center,
                            ),

                            const SizedBox(height: 20),

                            // Wardrobes Section
                            Expanded(
                              child: Consumer<WardrobeProvider>(
                                builder: (context, provider, child) {
                                  if (provider.isLoading &&
                                      provider.wardrobes.isEmpty) {
                                    return const Center(
                                      child: CircularProgressIndicator(
                                        color: Colors.white,
                                      ),
                                    );
                                  }

                                  if (provider.wardrobes.isEmpty) {
                                    return _buildEmptyState(context, provider);
                                  }

                                  return _buildWardrobesList(context, provider);
                                },
                              ),
                            ),

                            const SizedBox(height: 12),

                            // Create Wardrobe Button
                            Consumer<WardrobeProvider>(
                              builder: (context, provider, child) {
                                return ElevatedButton(
                                  onPressed: provider.hasReachedLimit
                                      ? null
                                      : () async {
                                          await Navigator.push(
                                            context,
                                            MaterialPageRoute(
                                              builder: (context) =>
                                                  const CreateWardrobeScreen(),
                                            ),
                                          );
                                          // Refresh wardrobes after returning
                                          _refreshWardrobes();
                                        },
                                  style: ElevatedButton.styleFrom(
                                    backgroundColor: Colors.white,
                                    foregroundColor: const Color(0xFF7C3AED),
                                    padding: const EdgeInsets.symmetric(
                                        vertical: 16),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(12),
                                    ),
                                    elevation: 0,
                                  ),
                                  child: Text(
                                    provider.hasReachedLimit
                                        ? 'Max 2 Wardrobes (Upgrade to add more)'
                                        : 'Create Wardrobe',
                                    style: const TextStyle(
                                      fontSize: 16,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                );
                              },
                            ),

                            const SizedBox(height: 12),

                            // Suggestions Button
                            OutlinedButton.icon(
                              onPressed: () {
                                Navigator.push(
                                  context,
                                  MaterialPageRoute(
                                    builder: (context) =>
                                        const SuggestionScreen(),
                                  ),
                                );
                              },
                              icon: const Icon(Icons.lightbulb_outline),
                              label: const Text('View Suggestions'),
                              style: OutlinedButton.styleFrom(
                                foregroundColor: Colors.white,
                                side: const BorderSide(
                                    color: Colors.white, width: 2),
                                padding:
                                    const EdgeInsets.symmetric(vertical: 16),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(12),
                                ),
                              ),
                            ),

                            const SizedBox(height: 12),
                          ],
                        ),
                      ),
                    );
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildEmptyState(BuildContext context, WardrobeProvider provider) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Icon(
          Icons.inventory_2,
          size: 80,
          color: Colors.white.withValues(alpha: 0.5),
        ),
        const SizedBox(height: 24),
        const Text(
          'No Wardrobes Yet',
          style: TextStyle(
            color: Colors.white,
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
        const SizedBox(height: 8),
        Text(
          'Create your first wardrobe to get started!',
          style: TextStyle(
            color: Colors.white.withValues(alpha: 0.8),
            fontSize: 14,
          ),
          textAlign: TextAlign.center,
        ),
      ],
    );
  }

  Widget _buildWardrobesList(BuildContext context, WardrobeProvider provider) {
    return ListView.builder(
      itemCount: provider.wardrobes.length,
      itemBuilder: (context, index) {
        final wardrobe = provider.wardrobes[index];
        return _buildWardrobeCard(context, wardrobe);
      },
    );
  }

  Widget _buildWardrobeCard(BuildContext context, Wardrobe wardrobe) {
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: Colors.white.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: Colors.white.withValues(alpha: 0.2),
        ),
      ),
      child: ListTile(
        leading: Container(
          width: 50,
          height: 50,
          decoration: BoxDecoration(
            color: Colors.white.withValues(alpha: 0.15),
            borderRadius: BorderRadius.circular(12),
          ),
          child: const Icon(
            Icons.checkroom,
            color: Colors.white,
            size: 28,
          ),
        ),
        title: Text(
          wardrobe.title,
          style: const TextStyle(
            color: Colors.white,
            fontSize: 16,
            fontWeight: FontWeight.bold,
          ),
        ),
        subtitle: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const SizedBox(height: 4),
            Text(
              wardrobe.location,
              style: TextStyle(
                color: Colors.white.withValues(alpha: 0.8),
                fontSize: 12,
              ),
            ),
            const SizedBox(height: 2),
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 8,
                    vertical: 2,
                  ),
                  decoration: BoxDecoration(
                    color: Colors.white.withValues(alpha: 0.2),
                    borderRadius: BorderRadius.circular(4),
                  ),
                  child: Text(
                    wardrobe.season,
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 10,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
                const SizedBox(width: 8),
                Text(
                  '${wardrobe.clothCount} clothes',
                  style: TextStyle(
                    color: Colors.white.withValues(alpha: 0.8),
                    fontSize: 10,
                  ),
                ),
              ],
            ),
          ],
        ),
        trailing: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            IconButton(
              icon: const Icon(Icons.delete_outline, color: Colors.red),
              onPressed: () => _deleteWardrobe(wardrobe),
              tooltip: 'Delete wardrobe',
              iconSize: 20,
            ),
            Icon(
              Icons.arrow_forward_ios,
              color: Colors.white.withValues(alpha: 0.8),
              size: 16,
            ),
          ],
        ),
        onTap: () {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (context) => WardrobeDetailScreen(wardrobe: wardrobe),
            ),
          );
        },
      ),
    );
  }
}
